### PR TITLE
minar platform should depend on cmsis-core conditionally

### PR DESCRIPTION
**Pull request by rgrover**
And it should depend on minar-platform-posix.

@bogdanm @autopulated

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by rgrover** [comment]
thanks @bogdanm.
Have you published this?

**Comment by rgrover** [comment]
@bogdanm can you please publish this? :)

**Comment by bogdanm** [comment]
What kind of version do you want to apply for this change? Minor or patch?

**Comment by rgrover** [comment]
could you please publish it as a patch?

**Comment by autopulated** [comment]
Patch as this is backwards compatible, and our convention for 0.x versions is that we use minor for breaking changes (we'll use the semver rules for >=1.x versions, where minor versions are backwards compatible new features, and patch versions are bugfixes: at that point we'll normally use the ^ specifier for dependencies, so that backwards-compatible updates are transparent).

**Comment by bogdanm** [comment]
Published.

**Pull request merged**
